[[redirects]]
  from = "/api/*"
  to = "https://us-central1-aiot-fit-xlab.cloudfunctions.net/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[redirects]]
  from = "/api/*"
  to = "/"
  status = 401
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  [redirects.headers]
    X-From = "Netlify"